name: Overwrite some file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Fetch data with curl
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # Access the JWT token from secrets
        run: |
          echo "CURL_OUTPUT=$(curl -X GET -H "Authorization: Bearer $JWT_TOKEN" "$CARD_WEEKLY_ENDPOINT")" >> $GITHUB_OUTPUT
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ./weekly-cards.html
          write-mode: overwrite
          contents: ${{ steps.fetch-data.outputs.CURL_OUTPUT }}
      - name: Commit files
        run: |
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
